DO $$ BEGIN
CREATE TYPE concordium_transaction_status AS ENUM (
   'pending',
   'finalized',
   'missing'
   );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
CREATE TYPE concordium_event_type AS ENUM (
    'token_map',
    'deposit',
    'withdraw',
    'grant_role',
    'revoke_role'
   );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
CREATE TYPE ethereum_transaction_status AS ENUM (
    'pending',
    'confirmed',
    'missing'
   );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
CREATE TYPE network AS ENUM (
    'ethereum',
    'concordium'
   );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS concordium_transactions (
       id SERIAL8 PRIMARY KEY UNIQUE,
       tx_hash BYTEA NOT NULL,
       -- The transaction on Ethereum that triggered sending this transaction.
       origin_tx_hash BYTEA NOT NULL,
       -- The actual transaction, for retries. This is signed already
       -- so cannot be manipulated.
       tx BYTEA NOT NULL,
       -- when the transaction was inserted
       timestamp INT8 NOT NULL,
       status concordium_transaction_status NOT NULL,
       CONSTRAINT concordium_transactions_tx_hash_unique UNIQUE (tx_hash)
       );

CREATE TABLE IF NOT EXISTS concordium_events (
       id SERIAL8 PRIMARY KEY UNIQUE,
       -- Hash of the transaction that logged the event. In principle
       -- a transaction can emit multiple events.
       tx_hash BYTEA NOT NULL,
       -- Event index of the event if present. This is only for events
       -- generated by the concordium contracts. Meaning Withdraw events.
       event_index INT8,
       -- The type of event.
       event_type concordium_event_type NOT NULL,
       -- Serialized event, exactly as logged by the contract.
       event_data BYTEA NOT NULL,
       -- Whether the event has already been processed on the Ethereum side.
       -- This is only meaningful for Withdraw events.
       processed BOOL NOT NULL,
       -- The latest Merkle root registered in the Ethereum contract that
       -- contains the event. Only applies to Withdraw events. NULL means that
       -- it is not yet registered.
       root BYTEA,
       pending_root BYTEA
       );

CREATE TABLE IF NOT EXISTS ethereum_transactions (
       id SERIAL8 PRIMARY KEY UNIQUE,
       tx_hash BYTEA NOT NULL,
       -- The actual transaction, for retries. This is signed already
       -- so cannot be manipulated.
       tx BYTEA NOT NULL,
       -- when the transaction was inserted
       timestamp INT8 NOT NULL,
       status ethereum_transaction_status NOT NULL,
       CONSTRAINT ethereum_transactions_tx_hash_unique UNIQUE (tx_hash)
       );

CREATE TABLE IF NOT EXISTS checkpoints (
       network network PRIMARY KEY UNIQUE,
       last_processed_height INT8 NOT NULL
);

CREATE TABLE IF NOT EXISTS merkle_roots (
       id SERIAL8 PRIMARY KEY UNIQUE,
       root BYTEA NOT NULL
);


-- TODO: Add index for concordium_events to easily filter out withdraws.
